### ISSUE TITLE
Supporting headless Chrome?

### ISSUE THREAD

**Issue by rauschma** [MartinPaulEve/CaSSius#2]
Recent versions of Chrome can be run in headless mode, from the command line. I’ve used it successfully to produce great-looking slides via Reveal.js (notably, pagination works well). This is how I invoke it on my Mac:

```text
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome  --headless --disable-gpu --print-to-pdf=/Users/rauschma/tmp/slides.pdf http://localhost:1234/slides.html?print-pdf
```

Alas, Chrome doesn’t implement CSS Regions and it looks like they are losing losing support: https://alistapart.com/blog/post/css-regions-considered-harmful

In light of these developments – what are the plans for CaSSius going forward?

Since I’ve read about the idea, I’m intrigued by the possibility of producing print-ready PDFs (with cross-references mentioning page numbers). Having an affordable option would open up a lot of possibilities for content creators.

**Comment by MartinPaulEve** [comment]
Hi Axel,

I'll try this with headless Chrome when I get a chance. The lack of regions
support isn't a problem: we use a javascript shim to emulate this
functionality.

That said, I'll note that we already have headless support using
wkhtmltopdf...

Best wishes,

Martin

**Comment by rauschma** [comment]
Thanks for humoring me!

**Comment by MartinPaulEve** [comment]
OK, so I had a look at this today and, unfortunately, there's a blocker: https://stackoverflow.com/questions/45748323/use-chrome-print-to-pdf-headless-to-print-html-too-quickly

Without a way to delay Chrome, we can't run the repagination engine, so you end up with either a set of blank pages or a set of overflowing text blocks. If there is a flag to delay Chrome, then we could do this but I can't see it for now.
